from __future__ import annotations

POIS = [
    {
        "id": "east_gate",
        "name": "东宫门",
        "name_en": "East Palace Gate",
        "x": 16,
        "y": 68,
        "tags": ["入口", "宫廷", "路线起点"],
        "open_time": "06:30-18:00",
        "visit_minutes": 12,
        "image_url": "",
        "summary": "东宫门是颐和园主要入口之一，门额由光绪皇帝题写，是进入宫廷区的第一处标志性空间。",
        "story": "从东宫门进入，游客会先抵达仁寿殿一带。这里适合承担 demo 的起点角色：既能说明皇家园林的礼制入口，也能自然引出勤政、游赏和长廊线路。",
    },
    {
        "id": "renshou_hall",
        "name": "仁寿殿",
        "name_en": "Hall of Benevolence and Longevity",
        "x": 25,
        "y": 62,
        "tags": ["宫廷", "历史", "建筑"],
        "open_time": "08:30-17:00",
        "visit_minutes": 18,
        "image_url": "",
        "summary": "仁寿殿是清代帝后在颐和园处理政务、接见臣工的重要建筑。",
        "story": "仁寿殿原名勤政殿，重建后改为仁寿殿。它体现了皇家园林并不只是游乐空间，也承载政治礼仪和日常政务。",
    },
    {
        "id": "dehe_garden",
        "name": "德和园",
        "name_en": "Garden of Virtue and Harmony",
        "x": 30,
        "y": 55,
        "tags": ["戏曲", "建筑", "文化"],
        "open_time": "08:30-17:00",
        "visit_minutes": 22,
        "image_url": "",
        "summary": "德和园以大戏楼闻名，是清代宫廷戏曲活动的重要场所。",
        "story": "大戏楼结构复杂，舞台上下三层，能表现升降、云雾和水法等戏曲机关。MVP 不做沉浸戏曲，但这里很适合作为后续 MR 戏曲体验的预留节点。",
    },
    {
        "id": "long_corridor",
        "name": "长廊",
        "name_en": "Long Corridor",
        "x": 43,
        "y": 48,
        "tags": ["绘画", "湖景", "经典"],
        "open_time": "06:30-18:00",
        "visit_minutes": 25,
        "image_url": "",
        "summary": "长廊沿昆明湖北岸展开，以彩画和湖山视野著称，是颐和园最经典的游赏线。",
        "story": "长廊全长约七百余米，梁枋上绘有大量山水、人物和典故画面。它连接宫廷区与万寿山前山，是路线规划中最稳定的中轴节点。",
    },
    {
        "id": "paiyun_hall",
        "name": "排云殿",
        "name_en": "Hall of Dispelling Clouds",
        "x": 52,
        "y": 39,
        "tags": ["建筑", "中轴", "历史"],
        "open_time": "08:30-17:00",
        "visit_minutes": 18,
        "image_url": "",
        "summary": "排云殿位于万寿山前山中轴，是连接湖岸和佛香阁的重要礼仪建筑群。",
        "story": "排云殿建筑群层层抬升，形成从湖面到山体的视觉引导。站在这里回望昆明湖，可以理解颐和园借景与轴线组织的设计。",
    },
    {
        "id": "foxiang_pavilion",
        "name": "佛香阁",
        "name_en": "Tower of Buddhist Incense",
        "x": 55,
        "y": 29,
        "tags": ["地标", "建筑", "俯瞰"],
        "open_time": "08:30-17:00",
        "visit_minutes": 28,
        "image_url": "",
        "summary": "佛香阁是颐和园最醒目的地标建筑，位于万寿山南坡高处。",
        "story": "佛香阁八面三层，依山而建，具有很强的视觉统领作用。识别讲解 demo 可以优先选择这里，因为它的外观特征明显，用户也容易理解识别结果。",
    },
    {
        "id": "kunming_lake",
        "name": "昆明湖",
        "name_en": "Kunming Lake",
        "x": 49,
        "y": 74,
        "tags": ["湖景", "休闲", "摄影"],
        "open_time": "06:30-18:00",
        "visit_minutes": 30,
        "image_url": "",
        "summary": "昆明湖是颐和园水面核心，承担游览、观景和空间组织功能。",
        "story": "昆明湖开阔的水面让万寿山建筑群获得完整倒影和远景。轻松路线可以把它作为休息和拍照节点。",
    },
    {
        "id": "seventeen_arch_bridge",
        "name": "十七孔桥",
        "name_en": "Seventeen-Arch Bridge",
        "x": 66,
        "y": 78,
        "tags": ["桥梁", "摄影", "湖景"],
        "open_time": "06:30-18:00",
        "visit_minutes": 20,
        "image_url": "",
        "summary": "十七孔桥连接东堤和南湖岛，桥身节奏鲜明，是昆明湖区域的重要景观。",
        "story": "桥上石狮数量众多，冬至前后还常出现夕阳穿洞的著名景象。它适合被推荐给摄影兴趣游客。",
    },
    {
        "id": "suzhou_street",
        "name": "苏州街",
        "name_en": "Suzhou Street",
        "x": 44,
        "y": 18,
        "tags": ["市井", "水街", "文化"],
        "open_time": "08:30-17:00",
        "visit_minutes": 26,
        "image_url": "",
        "summary": "苏州街模拟江南水街风貌，是皇家园林中富有生活气息的商业街景。",
        "story": "苏州街以水道为中心，两岸店铺相对，体现皇家园林对江南景观的再造。它适合文化体验和亲子路线。",
    },
    {
        "id": "xiequ_garden",
        "name": "谐趣园",
        "name_en": "Garden of Harmonious Pleasures",
        "x": 35,
        "y": 31,
        "tags": ["园林", "江南", "安静"],
        "open_time": "08:30-17:00",
        "visit_minutes": 24,
        "image_url": "",
        "summary": "谐趣园是一处精巧的园中园，以水院、游廊和小尺度景观取胜。",
        "story": "谐趣园借鉴江南园林手法，空间曲折、尺度亲近。它适合安静深度游，也能平衡佛香阁一带的人流。",
    },
]


EDGES = [
    ("east_gate", "renshou_hall", 320, 5),
    ("renshou_hall", "dehe_garden", 240, 4),
    ("dehe_garden", "long_corridor", 520, 8),
    ("long_corridor", "paiyun_hall", 430, 7),
    ("paiyun_hall", "foxiang_pavilion", 360, 9),
    ("long_corridor", "kunming_lake", 260, 4),
    ("kunming_lake", "seventeen_arch_bridge", 980, 15),
    ("foxiang_pavilion", "xiequ_garden", 820, 14),
    ("xiequ_garden", "suzhou_street", 610, 10),
    ("suzhou_street", "dehe_garden", 930, 16),
    ("paiyun_hall", "kunming_lake", 390, 6),
    ("east_gate", "long_corridor", 1180, 18),
]


KNOWLEDGE_DOCS = [
    {
        "id": "faq_opening",
        "title": "开放与游览建议",
        "poi_id": None,
        "language": "zh",
        "tags": ["开放", "建议", "路线"],
        "content": "颐和园面积较大，demo 路线建议按 60、90、150 分钟三档规划。初次游览可从东宫门进入，经仁寿殿、德和园、长廊、排云殿、佛香阁，再根据体力选择昆明湖或苏州街。",
    },
    {
        "id": "faq_photo",
        "title": "拍照点推荐",
        "poi_id": None,
        "language": "zh",
        "tags": ["摄影", "湖景", "推荐"],
        "content": "摄影兴趣游客可优先选择佛香阁、昆明湖和十七孔桥。佛香阁适合拍地标，昆明湖适合拍开阔水面，十七孔桥适合日落和桥体线条。",
    },
    {
        "id": "faq_family",
        "title": "亲子路线建议",
        "poi_id": None,
        "language": "zh",
        "tags": ["亲子", "轻松", "路线"],
        "content": "亲子或轻松路线应减少爬山，可从东宫门到仁寿殿、德和园、长廊，再到昆明湖休息。若时间充足，可加入十七孔桥或苏州街。",
    },
]
